# Generated by Django 6.0.6 on 2026-06-23 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
            ],
            options={
                'db_table': 'pessoa',
            },
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=50)),
                ('nivel', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'personagem',
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo_conta', models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor')], default='aluno', max_length=20)),
            ],
            options={
                'db_table': 'conta',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'disciplina',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.IntegerField()),
                ('descricao', models.TextField()),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.pessoa')),
                ('moedas', models.IntegerField(default=0)),
                ('itens', models.ManyToManyField(blank=True, related_name='alunos', to='api.item')),
            ],
            options={
                'db_table': 'aluno',
            },
            bases=('api.pessoa',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.pessoa')),
            ],
            options={
                'db_table': 'professor',
            },
            bases=('api.pessoa',),
        ),
        migrations.CreateModel(
            name='Arqueiro',
            fields=[
                ('personagem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.personagem')),
                ('destreza', models.IntegerField()),
            ],
            options={
                'db_table': 'arqueiro',
            },
            bases=('api.personagem',),
        ),
        migrations.CreateModel(
            name='Guerreiro',
            fields=[
                ('personagem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.personagem')),
                ('forca', models.IntegerField()),
            ],
            options={
                'db_table': 'guerreiro',
            },
            bases=('api.personagem',),
        ),
        migrations.CreateModel(
            name='Mago',
            fields=[
                ('personagem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.personagem')),
                ('inteligencia', models.IntegerField()),
            ],
            options={
                'db_table': 'mago',
            },
            bases=('api.personagem',),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='conta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.conta'),
        ),
        migrations.CreateModel(
            name='Quests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('alternativa_a', models.CharField(default='', max_length=255)),
                ('alternativa_b', models.CharField(default='', max_length=255)),
                ('alternativa_c', models.CharField(default='', max_length=255)),
                ('alternativa_d', models.CharField(default='', max_length=255)),
                ('recompensa', models.IntegerField(default=50)),
                ('resposta_correta', models.CharField(max_length=1)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disciplina')),
            ],
            options={
                'db_table': 'quests',
            },
        ),
        migrations.AddField(
            model_name='personagem',
            name='aluno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.aluno'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='alunos',
            field=models.ManyToManyField(related_name='disciplinas', to='api.aluno'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.professor'),
        ),
    ]
